#!/bin/bash

sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7 python3.7-dev python3.7-venv

sudo apt-get install llvm-8
sudo ln -s /usr/bin/llvm-config-8 /usr/local/bin/llvm-config
export LLVM_CONFIG=/usr/local/bin/llvm-config

sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
sudo apt-get install libatlas-base-dev
sudo apt-get install libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev
sudo apt-get install libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk
sudo apt-get install libharfbuzz-dev libfribidi-dev libxcb1-dev
sudo apt-get install gcc gfortran libopenblas-dev liblapack-dev
sudo apt-get install -y nano

python3.7 -m venv dsp-env
source dsp-env/bin/activate

pip3 install --upgrade pip
pip3 install wheel
pip3 install cython
pip3 install numpy
pip3 install pandas
pip3 install soundfile
pip3 install matplotlib
pip3 install sounddevice
pip3 install numba==0.48.0
pip3 install scipy
pip3 install librosa
pip3 install tqdm
pip3 install ipython
pip3 install adafruit-blinka
pip3 install adafruit-circuitpython-busdevice
pip3 install adafruit-circuitpython-register
